spring.application.name=auth-service
server.port=8081

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
jwt.token.access.token.expiry=3600000
jwt.token.refresh.token.expiry=86400000
spring.r2dbc.url=r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:auth_db}
spring.r2dbc.username=${POSTGRES_USER}
spring.r2dbc.password=${POSTGRES_PASSWORD}

app.issuer=Vora

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=vora@gmail.com
spring.mail.password=vora
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

bloom.filter.dlq.max-retries=3
notification.email.from=vora@gmail.com

jwt.rsa-key-pair-path=/etc/keys/jwt